const content = `
## Módulo 8 — Laboratorio: diagnóstico completo de problemas de red

### 🎯 Objetivos de aprendizaje

* Aplicar la metodología de troubleshooting OSI en un escenario real con múltiples fallos simultáneos.
* Diagnosticar y corregir un servicio web que no escucha en la interfaz correcta.
* Restaurar la resolución DNS usando \`/etc/resolv.conf\` y systemd-resolved.
* Interpretar correctamente la pérdida de ICMP en saltos intermedios sin confundirla con pérdida TCP real.
* Documentar cada hallazgo con evidencia de comandos antes de aplicar correcciones.

### ❓ El problema real

Un servidor nuevo fue desplegado ayer por el equipo de infraestructura. Esta mañana llegan tres tickets de soporte: el puerto 80 no es accesible desde el exterior aunque nginx está activo, los nombres de dominio internos no resuelven, y el equipo de backend reporta que la conexión al servicio de base de datos "es inestable". Tres problemas distintos, tres diagnósticos distintos. Este laboratorio los replica y los resuelve uno por uno.

### 📖 Preparación del laboratorio

Antes de iniciar, verifica el estado general del servidor:

\`\`\`bash
# Estado de interfaces
ip link show

# IPs asignadas
ip addr show

# Rutas activas
ip route show

# Servicios en escucha
ss -tlnp
\`\`\`

\`\`\`text
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 state UP
    inet 10.0.1.25/24 brd 10.0.1.255 scope global eth0

default via 10.0.1.1 dev eth0
10.0.1.0/24 dev eth0 proto kernel scope link

State   Recv-Q  Send-Q  Local Address:Port  Peer Address:Port  Process
LISTEN  0       128     0.0.0.0:22         0.0.0.0:*          users:(("sshd",pid=1100))
LISTEN  0       511     127.0.0.1:80       0.0.0.0:*          users:(("nginx",pid=3201))
\`\`\`

La vista inicial ya revela el primer problema: nginx escucha solo en \`127.0.0.1:80\`.

### 📖 Problema 1: Puerto 80 no accesible externamente

**Síntoma:** SSH al servidor funciona. Desde fuera, \`curl http://10.0.1.25\` no responde.

#### Paso 1 — Confirmar el síntoma localmente

\`\`\`bash
# Desde el propio servidor: funciona
curl -s -o /dev/null -w "%{http_code}" http://127.0.0.1/
\`\`\`

\`\`\`text
200
\`\`\`

\`\`\`bash
# Simular acceso externo usando la IP de la interfaz
curl -s -o /dev/null -w "%{http_code}" http://10.0.1.25/
\`\`\`

\`\`\`text
curl: (7) Failed to connect to 10.0.1.25 port 80 after 0 ms: Connection refused
\`\`\`

Esto confirma que nginx responde localmente pero no en la IP de la interfaz.

#### Paso 2 — Identificar la causa

\`\`\`bash
ss -tlnp | grep :80
\`\`\`

\`\`\`text
LISTEN  0  511  127.0.0.1:80  0.0.0.0:*  users:(("nginx",pid=3201,fd=6))
\`\`\`

\`127.0.0.1:80\` — nginx está configurado para escuchar solo en loopback. Hay que encontrar qué bloque \`server\` define esto.

\`\`\`bash
grep -rn "listen" /etc/nginx/sites-enabled/
\`\`\`

\`\`\`text
/etc/nginx/sites-enabled/mi-app.conf:4:    listen 127.0.0.1:80;
\`\`\`

#### Paso 3 — Aplicar la corrección

\`\`\`bash
# Editar la directiva listen
nano /etc/nginx/sites-enabled/mi-app.conf
\`\`\`

Cambiar:

\`\`\`nginx
listen 127.0.0.1:80;
\`\`\`

Por:

\`\`\`nginx
listen 80;
\`\`\`

Esto equivale a \`listen 0.0.0.0:80\` — nginx escuchará en todas las interfaces.

\`\`\`bash
# Verificar sintaxis antes de recargar
nginx -t
\`\`\`

\`\`\`text
nginx: the configuration file /etc/nginx/nginx.conf syntax is ok
nginx: configuration file /etc/nginx/nginx.conf test is successful
\`\`\`

\`\`\`bash
# Recargar sin interrumpir conexiones activas
systemctl reload nginx
\`\`\`

#### Paso 4 — Verificar la corrección

\`\`\`bash
ss -tlnp | grep :80
\`\`\`

\`\`\`text
LISTEN  0  511  0.0.0.0:80  0.0.0.0:*  users:(("nginx",pid=3201,fd=6))
\`\`\`

\`\`\`bash
curl -s -o /dev/null -w "%{http_code}" http://10.0.1.25/
\`\`\`

\`\`\`text
200
\`\`\`

Problema 1 resuelto. Causa raíz: directiva \`listen\` con IP explícita de loopback en la configuración de nginx.

### 📖 Problema 2: DNS interno no resuelve

**Síntoma:** \`ping 8.8.8.8\` funciona pero \`ping google.com\` falla con "Name or service not known".

#### Paso 1 — Separar conectividad IP de resolución DNS

\`\`\`bash
# IP directa funciona — capa 3 está bien
ping -c 2 8.8.8.8
\`\`\`

\`\`\`text
PING 8.8.8.8 (8.8.8.8) 56(84) bytes of data.
64 bytes from 8.8.8.8: icmp_seq=1 ttl=118 time=12.3 ms
64 bytes from 8.8.8.8: icmp_seq=2 ttl=118 time=12.1 ms
\`\`\`

\`\`\`bash
# Nombre de dominio falla — DNS roto
ping -c 2 google.com
\`\`\`

\`\`\`text
ping: google.com: Name or service not known
\`\`\`

#### Paso 2 — Inspeccionar la configuración DNS

\`\`\`bash
cat /etc/resolv.conf
\`\`\`

\`\`\`text
# Generated by NetworkManager
nameserver 10.0.1.254
\`\`\`

\`\`\`bash
# Probar ese servidor DNS manualmente
dig +short @10.0.1.254 google.com
\`\`\`

\`\`\`text
;; connection timed out; no servers could be reached
\`\`\`

El nameserver configurado (\`10.0.1.254\`) no responde. Es una IP incorrecta — quizás de un servidor DNS interno que no existe en este entorno.

\`\`\`bash
# Confirmar con DNS público que el dominio existe
dig +short @8.8.8.8 google.com
\`\`\`

\`\`\`text
142.250.80.46
\`\`\`

El dominio existe y \`8.8.8.8\` responde correctamente. El problema es solo el nameserver mal configurado.

#### Paso 3 — Determinar qué gestiona /etc/resolv.conf

\`\`\`bash
ls -la /etc/resolv.conf
\`\`\`

\`\`\`text
lrwxrwxrwx 1 root root 39 Jan 15 10:00 /etc/resolv.conf -> /run/systemd/resolve/stub-resolv.conf
\`\`\`

Es un symlink gestionado por systemd-resolved. No se edita directamente.

\`\`\`bash
# Ver configuración de systemd-resolved
cat /etc/systemd/resolved.conf
\`\`\`

\`\`\`text
[Resolve]
DNS=10.0.1.254
FallbackDNS=
\`\`\`

#### Paso 4 — Corregir la configuración

\`\`\`bash
nano /etc/systemd/resolved.conf
\`\`\`

Cambiar:

\`\`\`ini
DNS=10.0.1.254
FallbackDNS=
\`\`\`

Por:

\`\`\`ini
DNS=8.8.8.8 1.1.1.1
FallbackDNS=9.9.9.9
\`\`\`

\`\`\`bash
systemctl restart systemd-resolved
\`\`\`

#### Paso 5 — Verificar la corrección

\`\`\`bash
dig +short google.com
\`\`\`

\`\`\`text
142.250.80.46
\`\`\`

\`\`\`bash
ping -c 2 google.com
\`\`\`

\`\`\`text
PING google.com (142.250.80.46) 56(84) bytes of data.
64 bytes from 142.250.80.46: icmp_seq=1 ttl=118 time=12.4 ms
\`\`\`

\`\`\`bash
curl -s -o /dev/null -w "%{http_code}" https://google.com
\`\`\`

\`\`\`text
301
\`\`\`

Problema 2 resuelto. Causa raíz: DNS configurado apuntaba a un servidor inexistente en este entorno. En sistemas con systemd-resolved, la corrección se aplica en \`/etc/systemd/resolved.conf\`, no en \`/etc/resolv.conf\` directamente.

### 📖 Problema 3: Pérdida de paquetes al backend

**Síntoma:** El equipo de backend reporta que las conexiones al servicio en \`10.0.2.50:5432\` (PostgreSQL) "se cortan intermitentemente".

#### Paso 1 — Medir pérdida con mtr

\`\`\`bash
mtr --report --report-cycles 60 10.0.2.50
\`\`\`

\`\`\`text
HOST: servidor-app                     Loss%   Snt   Last   Avg  Best  Wrst
  1. 10.0.1.1                          0.0%    60    0.8   0.9   0.7   1.4
  2. 172.16.0.1                        0.0%    60    2.1   2.3   1.9   4.1
  3. 10.0.2.1                         15.0%    60   18.4  19.1  17.2  45.2
  4. 10.0.2.50                         0.0%    60    3.2   3.4   3.0   5.1
\`\`\`

Resultado aparente: 15% de pérdida en el salto 3 (router \`10.0.2.1\`). El backend (\`10.0.2.50\`) muestra 0%.

#### Paso 2 — Interpretar el resultado correctamente

Este patrón es un falso positivo clásico. Cuando la pérdida aparece en un salto intermedio pero **no** en el salto siguiente, la explicación más probable es que el router intermedio está configurado con QoS (Quality of Service) que deprioritiza o descarta los paquetes ICMP que mtr usa para sus sondas.

Los routers de producción frecuentemente aplican esta configuración para reducir la carga del plano de control. El tráfico TCP de aplicación usa una cola diferente y pasa sin restricción.

\`\`\`text
Interpretación correcta:
  Hop 3: 15% pérdida ICMP  → router descarta ICMP bajo carga
  Hop 4: 0% pérdida         → el tráfico real llega sin pérdida

Interpretación INCORRECTA:
  "El router 10.0.2.1 está perdiendo el 15% de nuestros paquetes de base de datos"
\`\`\`

#### Paso 3 — Verificar conectividad TCP real al puerto del servicio

\`\`\`bash
# Probar el handshake TCP directamente
nc -zv 10.0.2.50 5432
\`\`\`

\`\`\`text
Connection to 10.0.2.50 5432 port [tcp/postgresql] succeeded!
\`\`\`

\`\`\`bash
# Prueba de múltiples intentos consecutivos
for i in \$(seq 1 10); do
  nc -zv -w 2 10.0.2.50 5432 2>&1 | tail -1
done
\`\`\`

\`\`\`text
Connection to 10.0.2.50 5432 port [tcp/postgresql] succeeded!
Connection to 10.0.2.50 5432 port [tcp/postgresql] succeeded!
Connection to 10.0.2.50 5432 port [tcp/postgresql] succeeded!
Connection to 10.0.2.50 5432 port [tcp/postgresql] succeeded!
Connection to 10.0.2.50 5432 port [tcp/postgresql] succeeded!
Connection to 10.0.2.50 5432 port [tcp/postgresql] succeeded!
Connection to 10.0.2.50 5432 port [tcp/postgresql] succeeded!
Connection to 10.0.2.50 5432 port [tcp/postgresql] succeeded!
Connection to 10.0.2.50 5432 port [tcp/postgresql] succeeded!
Connection to 10.0.2.50 5432 port [tcp/postgresql] succeeded!
\`\`\`

10 de 10 conexiones TCP exitosas. No hay pérdida real.

#### Paso 4 — Confirmar con curl si el protocolo lo permite

Para servicios HTTP, \`curl\` da información adicional sobre tiempos de conexión:

\`\`\`bash
curl -v --connect-timeout 5 http://10.0.2.50:8080/health 2>&1 | grep -E "Connected|< HTTP|curl:"
\`\`\`

\`\`\`text
* Connected to 10.0.2.50 port 8080
< HTTP/1.1 200 OK
\`\`\`

#### Paso 5 — Investigar la causa real de las desconexiones

Si TCP conecta sin pérdida pero la aplicación reporta cortes, el problema está en la capa de aplicación. Verificar:

\`\`\`bash
# Timeouts de conexión del pool de la aplicación
# (ejemplo para PostgreSQL con psql)
psql -h 10.0.2.50 -U appuser -d appdb -c "SHOW tcp_keepalives_idle;"
\`\`\`

\`\`\`text
 tcp_keepalives_idle
---------------------
 0
(1 row)
\`\`\`

\`tcp_keepalives_idle = 0\` significa que PostgreSQL usa el valor del sistema operativo. Si el SO tiene un keep-alive alto y hay un firewall con timeout de sesión corto, las conexiones idle se cierran silenciosamente por el firewall antes de que el keep-alive las detecte.

\`\`\`bash
# Ver keep-alive del sistema
sysctl net.ipv4.tcp_keepalive_time
sysctl net.ipv4.tcp_keepalive_intvl
sysctl net.ipv4.tcp_keepalive_probes
\`\`\`

\`\`\`text
net.ipv4.tcp_keepalive_time = 7200
net.ipv4.tcp_keepalive_intvl = 75
net.ipv4.tcp_keepalive_probes = 9
\`\`\`

\`tcp_keepalive_time = 7200\` — el kernel espera 2 horas antes de enviar el primer keep-alive. Si el firewall tiene timeout de sesión de 30 minutos, cerrará la conexión mucho antes.

\`\`\`bash
# Reducir keep-alive a 5 minutos para detectar conexiones muertas antes
sysctl -w net.ipv4.tcp_keepalive_time=300
sysctl -w net.ipv4.tcp_keepalive_intvl=30
sysctl -w net.ipv4.tcp_keepalive_probes=3
\`\`\`

Para hacer el cambio persistente:

\`\`\`bash
cat >> /etc/sysctl.d/99-network-tuning.conf << 'EOF'
net.ipv4.tcp_keepalive_time = 300
net.ipv4.tcp_keepalive_intvl = 30
net.ipv4.tcp_keepalive_probes = 3
EOF
\`\`\`

Problema 3 diagnosticado. Causa raíz: la pérdida de ICMP en saltos intermedios era un falso positivo (QoS del router). Las desconexiones reales se originan en el timeout de TCP keep-alive excesivo vs. el timeout del firewall de red.

### 📖 Resumen del diagnóstico completo

\`\`\`text
┌─────────────────────────────────────────────────────────────────────┐
│ PROBLEMA         │ SÍNTOMA              │ CAUSA              │ FIX  │
├─────────────────────────────────────────────────────────────────────┤
│ Puerto 80        │ Connection refused   │ listen 127.0.0.1   │ nginx│
│                  │ desde exterior       │ en lugar de 0.0.0.0│ conf │
├─────────────────────────────────────────────────────────────────────┤
│ DNS interno      │ Name not known       │ nameserver 10.0.1. │ rslv │
│                  │ para dominios        │ .254 no responde   │ conf │
├─────────────────────────────────────────────────────────────────────┤
│ Backend "inest." │ Cortes intermitentes │ keepalive_time=7200│ sysc │
│                  │ (ICMP loss falso)    │ > firewall timeout │ tl   │
└─────────────────────────────────────────────────────────────────────┘
\`\`\`

Orden de diagnóstico aplicado en cada problema:
1. Reproducir el síntoma con un comando concreto.
2. Aislar la capa afectada con la herramienta apropiada.
3. Identificar la causa exacta antes de modificar cualquier configuración.
4. Aplicar la corrección mínima necesaria.
5. Verificar con el mismo comando del paso 1.

### 📋 Lo que debes recordar

* \`ss -tlnp\` es el primer comando ante cualquier fallo de conectividad a un servicio — revela si el proceso escucha en la interfaz correcta.
* \`127.0.0.1:PUERTO\` significa solo loopback; \`0.0.0.0:PUERTO\` significa todas las interfaces.
* Cuando \`/etc/resolv.conf\` es un symlink a systemd-resolved, la configuración correcta va en \`/etc/systemd/resolved.conf\`.
* Pérdida de ICMP en un salto intermedio con 0% en el destino no es pérdida de TCP — es QoS del router.
* Siempre verifica con el protocolo real: \`nc -zv\` para TCP, \`curl\` para HTTP. No confíes únicamente en \`ping\` o \`mtr\`.
* \`tcp_keepalive_time = 7200\` (2 horas) frecuentemente supera el timeout de sesión de firewalls corporativos; reducirlo a 300 segundos es una práctica común en producción.

### 🧪 Autoevaluación

1. Un servicio muestra \`LISTEN 0.0.0.0:8080\` en \`ss -tlnp\` pero \`nmap -p 8080 servidor\` desde otra máquina devuelve \`filtered\`. ¿Cuál es la causa más probable y cómo la verificas?
2. \`/etc/resolv.conf\` es un symlink a \`/run/systemd/resolve/stub-resolv.conf\`. Editas el archivo directamente y agregas \`nameserver 8.8.8.8\`. Al reiniciar el servidor, el cambio desaparece. ¿Por qué? ¿Cuál es la forma correcta de persistirlo?
3. \`mtr --report\` a un host remoto muestra 30% de pérdida en el salto 6 y 0% en el salto 7 (destino). El equipo quiere abrir un ticket de incidencia contra el ISP. ¿Qué evidencia adicional debes recopilar antes de confirmar que existe un problema real?

---

1. La causa más probable es un firewall local (iptables o ufw) que bloquea el puerto 8080 para conexiones externas aunque el servicio esté escuchando. Se verifica con \`iptables -L INPUT -n -v | grep 8080\` o \`ufw status\` para ver si hay reglas DROP o si el puerto no está permitido explícitamente.
2. systemd-resolved regenera \`/run/systemd/resolve/stub-resolv.conf\` en cada arranque desde su propia configuración, sobreescribiendo los cambios manuales. La forma correcta de persistir la configuración es editar \`/etc/systemd/resolved.conf\` (sección \`[Resolve]\`, directiva \`DNS=\`) y ejecutar \`systemctl restart systemd-resolved\`.
3. Antes de abrir el ticket hay que demostrar que el problema afecta tráfico TCP real, no solo ICMP. Se debe ejecutar \`nc -zv destino puerto\` para el puerto de la aplicación, medir latencia y pérdida TCP con una herramienta como \`hping3 --tcp -p 443 -S --count 100 destino\`, y capturar varias ejecuciones de \`mtr --report\` en momentos distintos para descartar que sea pérdida temporal de ICMP por QoS. Solo si el tráfico TCP también muestra pérdida existe evidencia de un problema real en el camino.
`

export default content
